version: 2

models:
  - name: dim_product
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_customer
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_day
        tests:
          - unique
          - not_null

  - name: fact_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: user_id
      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_id

  - name: fact_purchases
    columns:
      - name: event_id
        tests:
          - unique
          - not_null